stages:
    - build_stage
    - deploy_stage

build:
    stage: build_stage
    script:
        - docker --version
        - docker build -t simple-flask-app .
    tags:
        - ec2
        - server

deploy:
    stage: deploy_stage
    script:
        - docker stop simple-flask-ap && docker rm simple-flask-app
        - docker run -d --name simple-flask-app -p 80:8080 simple-flask-app
        - docker login -u $USERNAME -p $TOKEN
        - docker tag pyapp $USERNAME/simple-flask-app
        - docker push $USERNAME/simple-flask-app
    tags:
        - ec2
        - server
