name: Build and Deploy Dockerised Flask App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.TOKEN }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t simple-flask-app-githubaction .

    - name: Tag Docker image
      run: docker tag simple-flask-app-githubaction ${{ secrets.USERNAME }}/simple-flask-app-githubaction

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.USERNAME }}/simple-flask-app-githubaction

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy Docker container to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        docker stop simple-flask-app-githubaction || true
        docker rm simple-flask-app-githubaction || true
        docker pull ${{ secrets.USERNAME }}/simple-flask-app-githubaction
        docker run -d --name simple-flask-app -p 80:8080 ${{ secrets.USERNAME }}/simple-flask-app-githubaction
        EOF
